### ISSUE TITLE
"Finish setting up Fresh" message persists on deno deploy

### ISSUE THREAD

**Issue by CarcajadaArtificial** [denoland/fresh#2845]
I'm attempting to deploy a fresh project to deno deploy and I keep getting this message:
```
Finish setting up Fresh
1. Go to your project in Deno Deploy and click the Settings tab.
2. In the Git Integration section, enter deno task build in the Build Command input.
3. Save the changes.
```
I've tried two things to make it happen:
1. I did EXACTLY what the message says, added a deno task build step and the message persists.
- Installation step: `deno task --cwd=www update:lunchbox`
- Build step: `deno task --cwd=www build`
- Entry point: `./www/main.ts`

2. I tried adding my own workflow based on the deploy workflow for the `www/` site in fresh.
```
name: Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: rc

      - name: Installation step
        working-directory: ./www
        run: "deno run -A jsr:@lunchbox/ui/upgrade"

      - name: Build step
        working-directory: ./www
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "lunchbox"
          entrypoint: "./www/main.ts"
          root: "."
```

Clearly both of my solution attempts contain a build step, so I don't know why the site insists that it still needs one. I'm in dire need of any help. Thank you.

- Link to repo: https://github.com/CarcajadaArtificial/lunchbox
- Link to site: https://lunchbox-qvxd52vvb9f2.deno.dev/
