### ISSUE TITLE
error: Function not implemented (os error 38)

### ISSUE THREAD

**Issue by AMATEURTOSS** [denoland/fresh#418]
i'm currently using M1 mac Air and docker
os version: `macOS Monterey 12.4`
docker version: `Docker version 20.10.16, build aa7e414`
docker-compose version: `docker-compose version 1.29.2, build 5becea4c`
# error step
## step 1
run `deno run -A -r https://fresh.deno.dev test`
## step 2
make docker-compose.yml
```
version: "3.3"
services:
  test:
    container_name: test
    image: denoland/deno:latest
    working_dir: /test
    ports:
      - "8000:8000"
    volumes:
      - ./test:/test
    entrypoint: >
        sh -c "deno task start"
```
## step 3
run `docker-compose up`

## then
you can see like below
```
Warning deno task is unstable and may drastically change in the future
Task start deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.
error: Function not implemented (os error 38)
```

**Comment by AMATEURTOSS** [comment]
i got it. there is no official deno image for arm architecture
so i use lukechannings/deno (https://github.com/LukeChannings/deno-arm64) image
```yaml
version: "3.3"
services:
  test:
    container_name: test
    image: lukechannings/deno:latest # changed
    working_dir: /test
    ports:
      - "8000:8000"
    volumes:
      - ./test:/test
    entrypoint: >
        sh -c "deno task start"
```
